
CREATE TABLE `ENDUSERS` (
 `USERID` int(11) NOT NULL AUTO_INCREMENT,
 `FIRSTNAME` varchar(50) NOT NULL,
 `LASTNAME` varchar(80) NOT NULL,
 `EMAIL` varchar(100) NOT NULL,
 `USERNAME` varchar(50) NOT NULL,
 `PASSWORD` varchar(260) NOT NULL,
 PRIMARY KEY (`USERID`),
 UNIQUE KEY `UK_EMAIL` (`EMAIL`),
 UNIQUE KEY `UK_USERNAME` (`USERNAME`),
 KEY `E_USERID` (`USERID`)
);


CREATE TABLE `LOCATIONS` (
 `LOCATIONID` int(11) NOT NULL AUTO_INCREMENT,
 `LOCATIONNAME` varchar(256) NOT NULL,
 PRIMARY KEY (`LOCATIONID`),
 KEY `L_LOCATIONID` (`LOCATIONID`)
);

CREATE TABLE `STATIONS` (
 `STATIONID` int(11) NOT NULL,
 `USERID` int(16) NOT NULL,
 `LOCATIONID` int(16) DEFAULT NULL,
 `NICKNAME` varchar(50) DEFAULT NULL,
 PRIMARY KEY (`STATIONID`),
 UNIQUE KEY `UK_NICKNAME` (`NICKNAME`),
 KEY `S_STATIONID` (`STATIONID`),
 KEY `S_USERID` (`USERID`),
 KEY `S_LOCATIONID` (`LOCATIONID`),
 CONSTRAINT `STATIONS_FK_USERID` FOREIGN KEY (`USERID`) REFERENCES `ENDUSERS` (`USERID`) ON UPDATE CASCADE,
 CONSTRAINT `STATIONS_FK_LOCATIONID` FOREIGN KEY (`LOCATIONID`) REFERENCES `LOCATIONS` (`LOCATIONID`) ON UPDATE CASCADE
);

CREATE TABLE `READINGS` (
 `READINGID` bigint(20) NOT NULL AUTO_INCREMENT,
 `STATIONID` int(16) NOT NULL,
 `RDATETIME` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
 `TEMPERATURE` varchar(25) DEFAULT NULL,
 `AIRPRESSURE` varchar(25) DEFAULT NULL,
 `AMBIENTLIGHT` varchar(25) DEFAULT NULL,
 `HUMIDITY` varchar(25) DEFAULT NULL,
 PRIMARY KEY (`READINGID`),
 KEY `R_READINGID` (`READINGID`),
 KEY `R_STATIONID` (`STATIONID`),
 CONSTRAINT `READINGS_FK_STATIONID` FOREIGN KEY (`STATIONID`) REFERENCES `STATIONS` (`STATIONID`) ON UPDATE CASCADE
);
