 DROP TABLE `READINGS`;
 
 CREATE TABLE `READINGS` (
 `READINGID` int(20) NOT NULL AUTO_INCREMENT,
 `STATIONID` int(16) NOT NULL,
 `RDATETIME` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
 `TEMPERATURE` double(10,4) DEFAULT NULL,
 `AIRPRESSURE` double(10,4) DEFAULT NULL,
 `AMBIENTLIGHT` double(10,4) DEFAULT NULL,
 `HUMIDITY` double(10,4) DEFAULT NULL,
 PRIMARY KEY (`READINGID`),
 KEY `R_READINGID` (`READINGID`),
 KEY `R_STATIONID` (`STATIONID`),
 CONSTRAINT `READINGS_FK_STATIONID` FOREIGN KEY (`STATIONID`) REFERENCES `STATIONS` (`STATIONID`) ON UPDATE CASCADE
);

