INSERT INTO WeatherDB.ENDUSERS (USERID, FIRSTNAME, LASTNAME, EMAIL, USERNAME, PASSWORD) VALUES ('1','Morne', 'Venter','28634748@student.g.nwu.ac.za','Morne111','root');
INSERT INTO WeatherDB.ENDUSERS (USERID, FIRSTNAME, LASTNAME, EMAIL, USERNAME, PASSWORD) VALUES ('2','Eon', 'Viljoen','eonviljoen.ev@gmail.com','EonBoy','root');
INSERT INTO WeatherDB.ENDUSERS (USERID, FIRSTNAME, LASTNAME, EMAIL, USERNAME, PASSWORD) VALUES ('3','Coenraad', 'Human','coen.human@gmail.com','CeonMan','root');

INSERT INTO WeatherDB.LOCATIONS (LOCATIONID, LOCATIONNAME) VALUES ('1', 'Eon Room');
INSERT INTO WeatherDB.LOCATIONS (LOCATIONID, LOCATIONNAME) VALUES ('2', 'Morne Room');
INSERT INTO WeatherDB.LOCATIONS (LOCATIONID, LOCATIONNAME) VALUES ('3', 'Coenraad Room');


INSERT INTO WeatherDB.STATIONS (STATIONID,USERID, LOCATIONID, NICKNAME) VALUES ('10359807','1','2','McLovin');
INSERT INTO WeatherDB.STATIONS (STATIONID,USERID, LOCATIONID, NICKNAME) VALUES ('2347795','2','1','Spice Master');
INSERT INTO WeatherDB.STATIONS (STATIONID,USERID, LOCATIONID, NICKNAME) VALUES ('10359964','3','3','Cave Delver');


INSERT INTO WeatherDB.READINGS (READINGID, STATIONID, TEMPERATURE, AIRPRESSURE, AMBIENTLIGHT, HUMIDITY) VALUES ('1','10359807','32.2','250.04','0.34','0.5');
